### ISSUE TITLE
net.predict() Raises Error Calculating Dot Product; Theano Cannot Find MKL Lib

### ISSUE THREAD

**Issue by tylerpayne** [lmjohns3/theanets#54]
I am trying to use theanets to take advantage of its favorable speed in order to replace a slower ML library I was using (PyBrain). I have come across a confusing error that seems to be more of an issue between Anaconda and Theano but I was wondering if anyone here could provide any insight. 

Here is a link to an issue on the Theano repository https://github.com/Theano/Theano/issues/1871 dealing with a similar issue. The fix suggested in that thread is to set the DYLD_FALLBACK_LIBRARY_PATH to .../anaconda/lib. After doing this, though, my issue persists.

>>> import theanets
>>> import numpy as np
>>> x = np.array([1,2,3])
>>> net = theanets.Network(layers=[3,10,3])
>>> net.predict(x)
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '1480' (I am process '4543')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theanets/feedforward.py", line 556, in predict
    return self.feed_forward(x)[-1]
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theanets/feedforward.py", line 540, in feed_forward
    self._compile()
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theanets/feedforward.py", line 428, in _compile
    [self.x], self.hiddens + [self.y], updates=self.updates)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/compile/function.py", line 265, in function
    profile=profile)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1546, in orig_function
    defaults)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1409, in create
    _fn, _i, _o = self.linker.make_thunk(input_storage=input_storage_lists)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/link.py", line 531, in make_thunk
    output_storage=output_storage)[:3]
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 722, in make_thunk
    output_storage=node_output_storage)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1043, in make_thunk
    keep_lock=keep_lock)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 985, in __compile__
    keep_lock=keep_lock)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1423, in cthunk_factory
    key=key, fn=self.compile_cmodule_by_step, keep_lock=keep_lock)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1005, in module_from_key
    module = next(compile_steps)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1338, in compile_cmodule_by_step
    preargs=preargs)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2011, in compile_str
    return dlimport(lib_filename)
  File "/Users/tylerpayne/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 289, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', Dot22(x, W_0), '\n', 'dlopen(/Users/tylerpayne/.theano/compiledir_Darwin-14.0.0-x86_64-i386-64bit-i386-2.7.9-64/tmpkwsKlI/e72a390c58958feb2b036cde5102049d.so, 2): Library not loaded: libmkl_intel_lp64.dylib\n  Referenced from: /Users/tylerpayne/.theano/compiledir_Darwin-14.0.0-x86_64-i386-64bit-i386-2.7.9-64/tmpkwsKlI/e72a390c58958feb2b036cde5102049d.so\n  Reason: image not found', '[Dot22(x, W_0)]')

**Comment by andozone** [comment]
I have the same exact issue and setting the environment variable didn't help either. Did you find a way to fix it?

**Comment by gwulfs** [comment]
+1

**Comment by cranmer** [comment]
+1 why is the issue closed?

**Comment by cranmer** [comment]
see: https://github.com/ContinuumIO/anaconda-issues/issues/547
