### ISSUE TITLE
Problem running lstm_chime.py example

### ISSUE THREAD

**Issue by kjancsi** [lmjohns3/theanets#61]
The example crashes before training starts.

**Comment by lmjohns3** [comment]
Can you include more details, like a traceback? What happens exactly?

**Comment by akosv** [comment]
Sorry, here it comes:
> python lstm_chime.py 

I 2015-01-28 20:25:21 lstm-chime:26 attempting data copy from url: https://github.com/craffel/lstm_benchmarks/archive/master.zip
I 2015-01-28 20:25:40 theanets.layers:1046 initializing bdlstm1: 39<-> x 156
I 2015-01-28 20:25:40 theanets.layers:933 initializing bdlstm1_fw: 39 x 156
...
I 2015-01-28 20:25:40 theanets.main:212 --validate_every = 10
I 2015-01-28 20:25:40 theanets.main:212 --weight_l1 = 0
I 2015-01-28 20:25:40 theanets.main:212 --weight_l2 = 0

Traceback (most recent call last):
  File "lstm_chime.py", line 70, in <module>
    batches(scipy.io.netcdf_file(open(VALID_NC))))
  File "/Users/blah/Devel/theanets/theanets/main.py", line 258, in train
    for _ in self.itertrain(*args, **kwargs):
  File "/Users/blah/Devel/theanets/theanets/main.py", line 321, in itertrain
    opt = self.create_trainer(opt, **kwargs)
  File "/Users/blah/Devel/theanets/theanets/main.py", line 213, in create_trainer
    return factory(*args, **kw)
  File "/Users/blah/Devel/theanets/theanets/trainer.py", line 496, in __init__
    super(RmsProp, self).__init__(network, **kwargs)
  File "/Users/blah/Devel/theanets/theanets/trainer.py", line 257, in __init__
    super(SGD, self).__init__(network, **kwargs)
  File "/Users/blah/Devel/theanets/theanets/trainer.py", line 139, in __init__
    self.loss = network.loss(**kwargs)
  File "/Users/blah/Devel/theanets/theanets/feedforward.py", line 653, in loss
    hiddens = self.outputs[1:-1]
  File "/Users/blah/Devel/theanets/theanets/feedforward.py", line 403, in outputs
    return self._connect()[0]
  File "/Users/blah/Devel/theanets/theanets/feedforward.py", line 395, in _connect
    out, mon, upd = layer.output(inputs)
  File "/Users/blah/Devel/theanets/theanets/layers.py", line 363, in output
    out, mon, upd = self.transform(inputs)
  File "/Users/blah/Devel/theanets/theanets/layers.py", line 1073, in transform
    fx, fu = self.forward.transform(inputs)
ValueError: too many values to unpack

**Comment by kjancsi** [comment]
Sorry, here it comes:
```
> python lstm_chime.py 

I 2015-01-28 20:25:21 lstm-chime:26 attempting data copy from url: https://github.com/craffel/lstm_benchmarks/archive/master.zip
I 2015-01-28 20:25:40 theanets.layers:1046 initializing bdlstm1: 39<-> x 156
I 2015-01-28 20:25:40 theanets.layers:933 initializing bdlstm1_fw: 39 x 156
...
I 2015-01-28 20:25:40 theanets.main:212 --validate_every = 10
I 2015-01-28 20:25:40 theanets.main:212 --weight_l1 = 0
I 2015-01-28 20:25:40 theanets.main:212 --weight_l2 = 0

Traceback (most recent call last):
  File "lstm_chime.py", line 70, in <module>
    batches(scipy.io.netcdf_file(open(VALID_NC))))
  File "/Users/blah/Devel/theanets/theanets/main.py", line 258, in train
    for _ in self.itertrain(*args, **kwargs):
  File "/Users/blah/Devel/theanets/theanets/main.py", line 321, in itertrain
    opt = self.create_trainer(opt, **kwargs)
  File "/Users/blah/Devel/theanets/theanets/main.py", line 213, in create_trainer
    return factory(*args, **kw)
  File "/Users/blah/Devel/theanets/theanets/trainer.py", line 496, in __init__
    super(RmsProp, self).__init__(network, **kwargs)
  File "/Users/blah/Devel/theanets/theanets/trainer.py", line 257, in __init__
    super(SGD, self).__init__(network, **kwargs)
  File "/Users/blah/Devel/theanets/theanets/trainer.py", line 139, in __init__
    self.loss = network.loss(**kwargs)
  File "/Users/blah/Devel/theanets/theanets/feedforward.py", line 653, in loss
    hiddens = self.outputs[1:-1]
  File "/Users/blah/Devel/theanets/theanets/feedforward.py", line 403, in outputs
    return self._connect()[0]
  File "/Users/blah/Devel/theanets/theanets/feedforward.py", line 395, in _connect
    out, mon, upd = layer.output(inputs)
  File "/Users/blah/Devel/theanets/theanets/layers.py", line 363, in output
    out, mon, upd = self.transform(inputs)
  File "/Users/blah/Devel/theanets/theanets/layers.py", line 1073, in transform
    fx, fu = self.forward.transform(inputs)
ValueError: too many values to unpack
```

**Comment by lmjohns3** [comment]
Ah, excellent, thank you!
