### ISSUE TITLE
Hessian Free Optimizer does not work

### ISSUE THREAD

**Issue by dnth** [lmjohns3/theanets#62]
The hf optimizer does not work if implemented on the xor.py in the example folder.

Below is the error returned on the compiler:
Traceback (most recent call last):
  File "/home/camaro/workspace/theanets/xor.py", line 14, in <module>
    e.train([X, Y], optimize='hf', patience=5000, batch_size=4)
  File "/home/camaro/theanets/theanets/main.py", line 258, in train
    for _ in self.itertrain(*args, **kwargs):
  File "/home/camaro/theanets/theanets/main.py", line 321, in itertrain
    opt = self.create_trainer(opt, **kwargs)
  File "/home/camaro/theanets/theanets/main.py", line 213, in create_trainer
    return factory(*args, **kw)
  File "/home/camaro/theanets/theanets/trainer.py", line 681, in __init__
    None)
  File "/tmp/hf.py", line 66, in __init__
    Gv = gauss_newton_product(costs[0], p, v, s)
  File "/tmp/hf.py", line 14, in gauss_newton_product
    Jv = T.Rop(s, p, v)
  File "/home/camaro/Theano/theano/gradient.py", line 292, in Rop
    elif seen_nodes[out.owner][out.owner.outputs.index(out)] is None:
KeyError: None

**Comment by lmjohns3** [comment]
I'm going to go ahead and close this issue -- in my opinion the HF optimizer is dead, as more recent techniques (RMSProp, ESGD, Adam) have surpassed its performance in terms of both speed and accuracy. The HF code is also not compatible with Python 3.
